### ISSUE TITLE
Destinations in links with white-space should be enlosed in "<" and ">"

### ISSUE THREAD

**Issue by getreu** [izyuumi/html2md-rs#34]
## Expected behavior

The destination can only contain spaces if it is enclosed in pointy brackets:
[Commonmark: Example 489](https://spec.commonmark.org/0.31.2/#example-489)

```html
<p><a href="/my uri">link</a></p>
```

```md
[link](</my uri>)
```
and the destination can be percent encoded:

```html
<p><a href="/my%20uri">link</a></p>
```

```md
[link](</my uri>)
```

For percent decoding you can use: 

```rust
use percent_encoding::percent_decode_str;
```

from the crate [percent-encoding](https://crates.io/crates/percent-encoding). 
You can find a sample code [here](https://github.com/getreu/tp-note/blob/58a6218d129daeed53662f955e047b5fc7bb731d/tpnote-lib/src/html.rs#L232C1-L254C10).

## Current behavior

No pointy brackets are rendered when the destination has white-space.

**Comment by izyuumi** [comment]
Thank you for submitting such a detailed and well-documented issue! I really appreciate you including:
- The expected behavior with specific CommonMark references
- Clear examples of both pointy bracket and percent-encoded scenarios
- The helpful suggestion about using the `percent-encoding` crate

I'll work on implementing this according to the CommonMark specification you referenced. Thanks for making it easier to understand the exact requirements! 👍

**Comment by getreu** [comment]
Thank you @izyuumi
